# Generated by Django 5.2.18 on 2026-10-06 14:39

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('territoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Un compte existe déjà avec ce numéro de téléphone.'}, max_length=128, region=None, unique=True, verbose_name='téléphone')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenoms', models.CharField(max_length=150, verbose_name='prénoms')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='adresse e-mail')),
                ('role', models.CharField(choices=[('CITOYEN', 'Citoyen'), ('AGENT', 'Agent municipal'), ('ADMIN_MAIRIE', 'Administrateur mairie'), ('ORGANISATION', 'Organisation')], default='CITOYEN', max_length=20, verbose_name='rôle')),
                ('telephone_verifie', models.BooleanField(default=False, verbose_name='téléphone vérifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name="accès à l'administration")),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('quartier_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='territoire.quartier', verbose_name='quartier de résidence')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['nom', 'prenoms'],
            },
            managers=[
                ('objects', apps.accounts.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('token_fcm', models.CharField(max_length=255, unique=True, verbose_name='jeton FCM')),
                ('plateforme', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10, verbose_name='plateforme')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'appareil',
                'verbose_name_plural': 'appareils',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('sigle', models.CharField(blank=True, max_length=50, verbose_name='sigle')),
                ('type', models.CharField(choices=[('ONG', 'ONG'), ('OSC', 'OSC'), ('AUTRE', 'Autre')], max_length=10, verbose_name='type')),
                ('numero_enregistrement', models.CharField(error_messages={'unique': "Une organisation existe déjà avec ce numéro d'enregistrement."}, max_length=100, unique=True, verbose_name="numéro d'enregistrement")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='adresse e-mail')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisations/logos/', verbose_name='logo')),
                ('statut_habilitation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('HABILITEE', 'Habilitée'), ('SUSPENDUE', 'Suspendue'), ('REVOQUEE', 'Révoquée')], default='EN_ATTENTE', max_length=20, verbose_name="statut d'habilitation")),
                ('date_habilitation', models.DateField(blank=True, null=True, verbose_name="date d'habilitation")),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="date d'expiration")),
                ('habilitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_habilitees', to=settings.AUTH_USER_MODEL, verbose_name='habilitée par')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='accounts.organisation', verbose_name='organisation'),
        ),
        migrations.CreateModel(
            name='ServiceMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('nom', models.CharField(error_messages={'unique': 'Un service porte déjà ce nom.'}, max_length=150, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'service municipal',
                'verbose_name_plural': 'services municipaux',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='accounts.servicemunicipal', verbose_name='service municipal'),
        ),
        migrations.CreateModel(
            name='CodeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('code_hash', models.CharField(max_length=128, verbose_name='empreinte du code')),
                ('motif', models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('REINITIALISATION_MDP', 'Réinitialisation du mot de passe')], max_length=30, verbose_name='motif')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('tentatives', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('utilise', models.BooleanField(default=False, verbose_name='utilisé')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_otp', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'code OTP',
                'verbose_name_plural': 'codes OTP',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['utilisateur', 'motif'], name='accounts_co_utilisa_3a8f9c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'AGENT'), _negated=True), ('service__isnull', False), _connector='OR'), name='utilisateur_agent_avec_service', violation_error_message='Un agent doit être rattaché à un service municipal.'),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'ORGANISATION'), _negated=True), ('organisation__isnull', False), _connector='OR'), name='utilisateur_organisation_avec_organisation', violation_error_message='Un compte organisation doit être rattaché à une organisation.'),
        ),
    ]
