# Generated by Django 5.2.18 on 2026-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='domaines',
            field=models.ManyToManyField(blank=True, related_name='organisations', to='referentiel.categorie', verbose_name="domaines d'intervention"),
        ),
    ]
