# Generated by Django 5.2.18 on 2026-10-06 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convertir_anciens_statuts(apps, schema_editor):
    """
    EN_ATTENTE et REVOQUEE disparaissent : ces organisations sont suspendues (jamais
    habilitées d'office), avec un motif qui garde la trace de l'ancien statut.
    """
    Organisation = apps.get_model("accounts", "Organisation")
    for ancien, libelle in (("EN_ATTENTE", "en attente"), ("REVOQUEE", "révoquée")):
        Organisation.objects.filter(statut_habilitation=ancien).update(
            statut_habilitation="SUSPENDUE",
            motif_suspension=f"Ancien statut « {libelle} » converti lors de la simplification "
            "des statuts d'habilitation.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_renommer_domaines_en_secteurs'),
        ('referentiel', '0002_renommer_categorie_en_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='motif_suspension',
            field=models.TextField(blank=True, help_text="Obligatoire quand l'organisation est suspendue, vidé à la réhabilitation.", verbose_name='motif de suspension'),
        ),
        migrations.RunPython(convertir_anciens_statuts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organisation',
            name='date_expiration',
            field=models.DateField(blank=True, help_text='Laisser vide pour une habilitation sans limite.', null=True, verbose_name="date d'expiration"),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date_habilitation',
            field=models.DateField(editable=False, null=True, verbose_name="date d'habilitation"),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='habilitee_par',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_habilitees', to=settings.AUTH_USER_MODEL, verbose_name='habilitée par'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='statut_habilitation',
            field=models.CharField(choices=[('HABILITEE', 'Habilitée'), ('SUSPENDUE', 'Suspendue')], default='HABILITEE', max_length=20, verbose_name="statut d'habilitation"),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('statut_habilitation', 'SUSPENDUE'), _negated=True), models.Q(('motif_suspension', ''), _negated=True), _connector='OR'), name='organisation_suspension_avec_motif', violation_error_message='Le motif de suspension est obligatoire.'),
        ),
    ]
