# Generated by Django 5.2.18 on 2026-10-07 11:40

import django.db.models.functions.text
from django.db import migrations, models



def normaliser_emails(apps, schema_editor):
    """E-mails existants en minuscules ; e-mail vide remplacé par « aucun » (NULL)."""
    Utilisateur = apps.get_model("accounts", "Utilisateur")
    for utilisateur in Utilisateur.objects.exclude(email__isnull=True):
        email = (utilisateur.email or "").strip().lower() or None
        if email != utilisateur.email:
            Utilisateur.objects.filter(pk=utilisateur.pk).update(email=email)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_habilitation_simplifiee'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('territoire', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normaliser_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, help_text='Identifiant de connexion de la mairie et des organisations ; facultatif pour les citoyens.', max_length=254, null=True, verbose_name='adresse e-mail'),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'CITOYEN'), models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), _connector='OR'), name='utilisateur_personnel_avec_email', violation_error_message="L'adresse e-mail est obligatoire pour la mairie et les organisations."),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='utilisateur_email_unique', violation_error_message='Un compte existe déjà avec cette adresse e-mail.'),
        ),
    ]
