# Generated by Django 5.2.18 on 2026-10-07 13:44

import django.db.models.deletion
from django.db import migrations, models


def remplir_commune_des_services(apps, schema_editor):
    """Les services existants sont rattachés à la commune, s'il n'y en a qu'une."""
    ServiceMunicipal = apps.get_model("accounts", "ServiceMunicipal")
    Commune = apps.get_model("territoire", "Commune")
    if not ServiceMunicipal.objects.filter(commune__isnull=True).exists():
        return
    if Commune.objects.count() != 1:
        raise RuntimeError("Des services existent : créez d'abord une seule commune pour les y rattacher.")
    ServiceMunicipal.objects.filter(commune__isnull=True).update(commune=Commune.objects.get())

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_connexion_par_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('territoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemunicipal',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='territoire.commune', verbose_name='commune'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='commune',
            field=models.ForeignKey(blank=True, help_text="Citoyen : commune choisie à l'inscription. Agent / admin : commune de sa mairie (vide pour un admin de la plateforme, qui voit toutes les communes).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habitants', to='territoire.commune', verbose_name='commune de résidence'),
        ),
        migrations.AlterField(
            model_name='servicemunicipal',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='nom'),
        ),
        migrations.AddConstraint(
            model_name='servicemunicipal',
            constraint=models.UniqueConstraint(fields=('commune', 'nom'), name='service_unique_par_commune', violation_error_message='Un service porte déjà ce nom dans cette commune.'),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'AGENT'), _negated=True), ('commune__isnull', False), _connector='OR'), name='utilisateur_agent_avec_commune', violation_error_message='Un agent doit être rattaché à la commune de sa mairie.'),
        ),
        migrations.RunPython(remplir_commune_des_services, migrations.RunPython.noop),
    ]
