# Generated by Django 5.2.18 on 2026-10-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_commune_obligatoire'),
        ('referentiel', '0002_renommer_categorie_en_secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='secteurs',
            field=models.ManyToManyField(blank=True, help_text="L'organisation ne voit que les signalements de ces secteurs (aucun secteur : aucun signalement).", related_name='organisations', to='referentiel.secteur', verbose_name="secteurs d'intervention"),
        ),
    ]
