# Generated by Django 5.2.18 on 2026-10-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        ('referentiel', '0002_renommer_categorie_en_secteur'),
        ('territoire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('titre', models.CharField(max_length=150, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('statut', models.CharField(choices=[('RECUE', 'Reçue'), ('A_L_ETUDE', "À l'étude"), ('RETENUE', 'Retenue'), ('NON_RETENUE', 'Non retenue')], default='RECUE', max_length=20, verbose_name='statut')),
                ('nb_soutiens', models.PositiveIntegerField(default=0, verbose_name='nombre de soutiens')),
                ('reponse_officielle', models.TextField(blank=True, verbose_name='réponse officielle')),
                ('repondu_le', models.DateTimeField(blank=True, null=True, verbose_name='répondu le')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('medias', models.ManyToManyField(blank=True, related_name='suggestions', to='medias.media', verbose_name='photos')),
                ('quartier', models.ForeignKey(blank=True, help_text='Vide : la suggestion concerne toute la commune.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='territoire.quartier', verbose_name='quartier')),
                ('repondu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_repondues', to=settings.AUTH_USER_MODEL, verbose_name='répondu par')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='referentiel.secteur', verbose_name='secteur')),
            ],
            options={
                'verbose_name': 'suggestion',
                'verbose_name_plural': 'suggestions',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Soutien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soutiens', to=settings.AUTH_USER_MODEL, verbose_name='citoyen')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soutiens', to='suggestions.suggestion', verbose_name='suggestion')),
            ],
            options={
                'verbose_name': 'soutien',
                'verbose_name_plural': 'soutiens',
            },
        ),
        migrations.CreateModel(
            name='SuiviSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('type_evenement', models.CharField(choices=[('CHANGEMENT_STATUT', 'Changement de statut'), ('REPONSE', 'Réponse de la mairie'), ('NOTE_INTERNE', 'Note interne')], max_length=20, verbose_name="type d'événement")),
                ('ancien_statut', models.CharField(blank=True, choices=[('RECUE', 'Reçue'), ('A_L_ETUDE', "À l'étude"), ('RETENUE', 'Retenue'), ('NON_RETENUE', 'Non retenue')], max_length=20, verbose_name='ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, choices=[('RECUE', 'Reçue'), ('A_L_ETUDE', "À l'étude"), ('RETENUE', 'Retenue'), ('NON_RETENUE', 'Non retenue')], max_length=20, verbose_name='nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('visible_citoyen', models.BooleanField(default=True, verbose_name='visible par le citoyen')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suivis_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='suggestions.suggestion', verbose_name='suggestion')),
            ],
            options={
                'verbose_name': 'suivi de suggestion',
                'verbose_name_plural': 'suivis de suggestions',
                'ordering': ['cree_le', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['statut'], name='suggestion_statut_idx'),
        ),
        migrations.AddConstraint(
            model_name='soutien',
            constraint=models.UniqueConstraint(fields=('suggestion', 'citoyen'), name='soutien_unique_par_citoyen', violation_error_message='Vous soutenez déjà cette suggestion.'),
        ),
        migrations.AddConstraint(
            model_name='suivisuggestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_evenement', 'NOTE_INTERNE'), _negated=True), ('visible_citoyen', False), _connector='OR'), name='suivi_suggestion_note_interne_invisible', violation_error_message="Une note interne n'est jamais visible par le citoyen."),
        ),
    ]
