# Generated by Django 5.2.18 on 2026-10-06 19:46

from django.db import migrations, models



def supprimer_suivis_de_statut(apps, schema_editor):
    """Les suggestions n'ont plus de statut : leurs anciens changements de statut disparaissent."""
    apps.get_model("suggestions", "SuiviSuggestion").objects.filter(type_evenement="CHANGEMENT_STATUT").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(supprimer_suivis_de_statut, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='suggestion',
            name='suggestion_statut_idx',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='suivisuggestion',
            name='ancien_statut',
        ),
        migrations.RemoveField(
            model_name='suivisuggestion',
            name='nouveau_statut',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='est_pertinente',
            field=models.BooleanField(db_index=True, default=False, verbose_name='jugée pertinente par la mairie'),
        ),
        migrations.AlterField(
            model_name='suivisuggestion',
            name='type_evenement',
            field=models.CharField(choices=[('REPONSE', 'Réponse de la mairie'), ('NOTE_INTERNE', 'Note interne')], max_length=20, verbose_name="type d'événement"),
        ),
    ]
