# Generated by Django 5.2.18 on 2026-10-07 13:44

import django.db.models.deletion
from django.db import migrations, models


def remplir_commune(apps, schema_editor):
    """Commune d'une suggestion existante : celle de son quartier, sinon de son auteur, sinon la seule commune."""
    Suggestion = apps.get_model("suggestions", "Suggestion")
    Commune = apps.get_model("territoire", "Commune")
    unique = Commune.objects.first() if Commune.objects.count() == 1 else None
    for suggestion in Suggestion.objects.filter(commune__isnull=True).select_related("quartier__arrondissement", "auteur"):
        commune_id = (
            (suggestion.quartier.arrondissement.commune_id if suggestion.quartier_id else None)
            or suggestion.auteur.commune_id
            or (unique.pk if unique else None)
        )
        if commune_id is None:
            raise RuntimeError(f"Impossible de déterminer la commune de la suggestion {suggestion.reference}.")
        Suggestion.objects.filter(pk=suggestion.pk).update(commune_id=commune_id)

class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_sans_statut_avec_pertinence'),
        ('territoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='commune',
            field=models.ForeignKey(help_text="Commune de l'auteur au moment de l'envoi (déduite du compte, jamais envoyée).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='territoire.commune', verbose_name='commune'),
        ),
        migrations.RunPython(remplir_commune, migrations.RunPython.noop),
    ]
