# Generated by Django 5.2.18 on 2026-10-06 19:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        ('referentiel', '0002_renommer_categorie_en_secteur'),
        ('signalements', '0001_initial'),
        ('suggestions', '0002_sans_statut_avec_pertinence'),
        ('territoire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('SUSPENDUE', 'Suspendue')], default='PLANIFIEE', max_length=20, verbose_name='statut')),
                ('taux_avancement', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name="taux d'avancement (%)")),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='début prévu')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='fin prévue')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='début réel')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='fin réelle')),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='budget (FCFA)')),
                ('source_financement', models.CharField(blank=True, max_length=255, verbose_name='source de financement')),
                ('prestataire', models.CharField(blank=True, max_length=255, verbose_name='prestataire')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('publie', models.BooleanField(default=False, verbose_name='publiée')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realisations_creees', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('quartiers', models.ManyToManyField(related_name='realisations', to='territoire.quartier', verbose_name='quartiers concernés')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realisations', to='referentiel.secteur', verbose_name='secteur')),
                ('signalements', models.ManyToManyField(blank=True, related_name='realisations', to='signalements.signalement', verbose_name='signalements liés')),
                ('suggestions', models.ManyToManyField(blank=True, related_name='realisations', to='suggestions.suggestion', verbose_name='suggestions liées')),
            ],
            options={
                'verbose_name': 'réalisation',
                'verbose_name_plural': 'réalisations',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='RealisationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('phase', models.CharField(choices=[('AVANT', 'Avant les travaux'), ('PENDANT', 'Pendant les travaux'), ('APRES', 'Après les travaux')], max_length=10, verbose_name='phase')),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='légende')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realisation_media', to='medias.media', verbose_name='média')),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='realisations.realisation', verbose_name='réalisation')),
            ],
            options={
                'verbose_name': 'média de réalisation',
                'verbose_name_plural': 'médias de réalisation',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='realisation',
            index=models.Index(fields=['publie', 'statut'], name='realisation_publie_statut_idx'),
        ),
        migrations.AddConstraint(
            model_name='realisation',
            constraint=models.CheckConstraint(condition=models.Q(('taux_avancement__lte', 100)), name='realisation_taux_max_100', violation_error_message="Le taux d'avancement ne peut pas dépasser 100 %."),
        ),
        migrations.AddConstraint(
            model_name='realisation',
            constraint=models.CheckConstraint(condition=models.Q(('date_debut_prevue__isnull', True), ('date_fin_prevue__isnull', True), ('date_fin_prevue__gte', models.F('date_debut_prevue')), _connector='OR'), name='realisation_dates_prevues_ordonnees', violation_error_message='La fin prévue ne peut pas précéder le début prévu.'),
        ),
        migrations.AddConstraint(
            model_name='realisation',
            constraint=models.CheckConstraint(condition=models.Q(('date_debut_reelle__isnull', True), ('date_fin_reelle__isnull', True), ('date_fin_reelle__gte', models.F('date_debut_reelle')), _connector='OR'), name='realisation_dates_reelles_ordonnees', violation_error_message='La fin réelle ne peut pas précéder le début réel.'),
        ),
        migrations.AddConstraint(
            model_name='realisation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='realisation_position_complete', violation_error_message='La latitude et la longitude vont ensemble.'),
        ),
        migrations.AddConstraint(
            model_name='realisation',
            constraint=models.CheckConstraint(condition=models.Q(('budget__isnull', True), ('budget__gte', 0), _connector='OR'), name='realisation_budget_positif', violation_error_message='Le budget ne peut pas être négatif.'),
        ),
    ]
