# Generated by Django 5.2.18 on 2026-10-07 13:44

import django.db.models.deletion
from django.db import migrations, models


def remplir_commune(apps, schema_editor):
    """La commune d'une réalisation existante est celle de ses quartiers."""
    Realisation = apps.get_model("realisations", "Realisation")
    for realisation in Realisation.objects.filter(commune__isnull=True):
        quartier = realisation.quartiers.select_related("arrondissement").first()
        if quartier is None:
            raise RuntimeError(f"Impossible de déterminer la commune de la réalisation {realisation.reference}.")
        Realisation.objects.filter(pk=realisation.pk).update(commune_id=quartier.arrondissement.commune_id)

class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0001_initial'),
        ('territoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realisations', to='territoire.commune', verbose_name='commune'),
        ),
        migrations.RunPython(remplir_commune, migrations.RunPython.noop),
    ]
