# Generated by Django 5.2.18 on 2026-10-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0002_communes'),
        ('territoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realisations', to='territoire.commune', verbose_name='commune'),
        ),
    ]
