# Generated by Django 5.2.18 on 2026-10-06 16:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('nom', models.CharField(error_messages={'unique': 'Une catégorie porte déjà ce nom.'}, max_length=100, unique=True, verbose_name='nom')),
                ('code', models.CharField(error_messages={'unique': 'Une catégorie utilise déjà ce code.'}, max_length=30, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône affichée par les applications.", max_length=50, verbose_name='icône')),
                ('couleur', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'La couleur doit être au format hexadécimal, par exemple #1E88E5.')], verbose_name='couleur')),
                ('pour_signalement', models.BooleanField(default=False, verbose_name='utilisable pour les signalements')),
                ('pour_suggestion', models.BooleanField(default=False, verbose_name='utilisable pour les suggestions')),
                ('pour_realisation', models.BooleanField(default=False, verbose_name='utilisable pour les réalisations')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='active')),
                ('service_par_defaut', models.ForeignKey(blank=True, help_text='Service auquel les nouveaux signalements de cette catégorie sont assignés.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='accounts.servicemunicipal', verbose_name='service par défaut')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
