# Generated by Django 5.2.18 on 2026-10-06 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_habilitation_simplifiee'),
        ('medias', '0001_initial'),
        ('referentiel', '0002_renommer_categorie_en_secteur'),
        ('territoire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('titre', models.CharField(blank=True, max_length=150, verbose_name='titre')),
                ('titre_genere', models.BooleanField(default=False, verbose_name='titre généré automatiquement')),
                ('description_texte', models.TextField(blank=True, verbose_name='description écrite')),
                ('anonyme', models.BooleanField(default=False, verbose_name='anonyme')),
                ('mode_localisation', models.CharField(choices=[('GPS', 'Position GPS'), ('MANUEL', 'Quartier et repère')], max_length=10, verbose_name='mode de localisation')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('precision_gps', models.PositiveIntegerField(blank=True, null=True, verbose_name='précision GPS (m)')),
                ('repere', models.CharField(blank=True, max_length=255, verbose_name='repère')),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('RECU', 'Reçu'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté'), ('DOUBLON', 'Doublon')], default='SOUMIS', max_length=20, verbose_name='statut')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='priorité')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='date de résolution')),
                ('agent_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_assignes', to=settings.AUTH_USER_MODEL, verbose_name='agent assigné')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signalements', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('description_audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signalement_audio', to='medias.media', verbose_name='description vocale')),
                ('doublon_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doublons', to='signalements.signalement', verbose_name='doublon de')),
                ('medias', models.ManyToManyField(blank=True, related_name='signalements', to='medias.media', verbose_name='photos et vidéos')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signalements', to='territoire.quartier', verbose_name='quartier')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signalements', to='referentiel.secteur', verbose_name='secteur')),
                ('service_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_assignes', to='accounts.servicemunicipal', verbose_name='service assigné')),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='SuiviSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('type_evenement', models.CharField(choices=[('CHANGEMENT_STATUT', 'Changement de statut'), ('ASSIGNATION', 'Assignation'), ('REPONSE', 'Réponse de la mairie'), ('NOTE_INTERNE', 'Note interne')], max_length=20, verbose_name="type d'événement")),
                ('ancien_statut', models.CharField(blank=True, choices=[('SOUMIS', 'Soumis'), ('RECU', 'Reçu'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté'), ('DOUBLON', 'Doublon')], max_length=20, verbose_name='ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, choices=[('SOUMIS', 'Soumis'), ('RECU', 'Reçu'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté'), ('DOUBLON', 'Doublon')], max_length=20, verbose_name='nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('visible_citoyen', models.BooleanField(default=True, verbose_name='visible par le citoyen')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suivis_signalements', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='signalements.signalement', verbose_name='signalement')),
            ],
            options={
                'verbose_name': 'suivi de signalement',
                'verbose_name_plural': 'suivis de signalements',
                'ordering': ['cree_le', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['statut'], name='signalement_statut_idx'),
        ),
        migrations.AddConstraint(
            model_name='signalement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('description_texte', ''), _negated=True), ('description_audio__isnull', False), _connector='OR'), name='signalement_avec_description', violation_error_message='Une description écrite ou vocale est obligatoire.'),
        ),
        migrations.AddConstraint(
            model_name='signalement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode_localisation', 'GPS'), _negated=True), models.Q(('latitude__isnull', False), ('longitude__isnull', False), ('precision_gps__isnull', False)), _connector='OR'), name='signalement_gps_complet', violation_error_message='La position GPS (latitude, longitude, précision) est incomplète.'),
        ),
        migrations.AddConstraint(
            model_name='suivisignalement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_evenement', 'NOTE_INTERNE'), _negated=True), ('visible_citoyen', False), _connector='OR'), name='suivi_signalement_note_interne_invisible', violation_error_message="Une note interne n'est jamais visible par le citoyen."),
        ),
    ]
