# Generated by Django 5.2.18 on 2026-10-07 13:44

import django.db.models.deletion
from django.db import migrations, models


def remplir_commune(apps, schema_editor):
    """La commune d'un signalement existant est celle de son quartier."""
    Signalement = apps.get_model("signalements", "Signalement")
    for signalement in Signalement.objects.filter(commune__isnull=True).select_related("quartier__arrondissement"):
        Signalement.objects.filter(pk=signalement.pk).update(commune_id=signalement.quartier.arrondissement.commune_id)

class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0001_initial'),
        ('territoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='commune',
            field=models.ForeignKey(help_text="Commune de l'auteur au moment de l'envoi (déduite du compte, jamais envoyée).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signalements', to='territoire.commune', verbose_name='commune'),
        ),
        migrations.RunPython(remplir_commune, migrations.RunPython.noop),
    ]
