# Generated by Django 5.2.18 on 2026-10-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0003_commune_obligatoire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='anonyme',
        ),
    ]
