# Generated by Django 5.2.18 on 2026-10-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0004_suppression_anonyme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='priorite',
        ),
    ]
