# Generated by Django 5.2.18 on 2026-10-06 17:06

import apps.medias.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('AUDIO', 'Audio')], max_length=10, verbose_name='type')),
                ('fichier', models.FileField(max_length=255, upload_to=apps.medias.models.chemin_fichier, verbose_name='fichier')),
                ('miniature', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.medias.models.chemin_miniature, verbose_name='miniature')),
                ('mime_type', models.CharField(max_length=100, verbose_name='type MIME')),
                ('taille_octets', models.PositiveIntegerField(verbose_name='taille (octets)')),
                ('duree_secondes', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée (secondes)')),
                ('largeur', models.PositiveIntegerField(blank=True, null=True, verbose_name='largeur (px)')),
                ('hauteur', models.PositiveIntegerField(blank=True, null=True, verbose_name='hauteur (px)')),
                ('statut', models.CharField(choices=[('TEMPORAIRE', 'Temporaire'), ('ATTACHE', 'Attaché')], default='TEMPORAIRE', max_length=20, verbose_name='statut')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medias', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'média',
                'verbose_name_plural': 'médias',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['statut', 'cree_le'], name='media_statut_cree_le_idx')],
            },
        ),
    ]
