-- =============================================================================
-- Voix du Citoyen — structure de la base de données (PostgreSQL 17)
--
-- Contenu : toutes les tables, contraintes et index + l'historique des migrations
-- Django (table django_migrations). Aucune donnée utilisateur.
--
-- Import dans une base vide :
--     psql -d <nom_de_la_base> -f base_de_donnees.sql
-- puis, depuis le projet :
--     python manage.py migrate     (crée les types de contenu et permissions Django)
--
-- La source de vérité reste les migrations du projet (apps/*/migrations/) :
-- pour une nouvelle installation, « python manage.py migrate » suffit.
-- =============================================================================

--
-- PostgreSQL database dump
--

\restrict x2UuphhWyfAMBqV4wGCs6becaC5JJHP1X8ht59lNO7FKeZaQoJcUTtss7LhNWuo

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_appareil; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_appareil (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    token_fcm character varying(255) NOT NULL,
    plateforme character varying(10) NOT NULL,
    actif boolean NOT NULL,
    utilisateur_id bigint NOT NULL
);


--
-- Name: accounts_appareil_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_appareil ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_appareil_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_codeotp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_codeotp (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    code_hash character varying(128) NOT NULL,
    motif character varying(30) NOT NULL,
    expire_le timestamp with time zone NOT NULL,
    tentatives smallint NOT NULL,
    utilise boolean NOT NULL,
    utilisateur_id bigint NOT NULL,
    CONSTRAINT accounts_codeotp_tentatives_check CHECK ((tentatives >= 0))
);


--
-- Name: accounts_codeotp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_codeotp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_codeotp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_organisation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_organisation (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    nom character varying(200) NOT NULL,
    sigle character varying(50) NOT NULL,
    type character varying(10) NOT NULL,
    numero_enregistrement character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    telephone character varying(128) NOT NULL,
    adresse character varying(255) NOT NULL,
    logo character varying(100),
    statut_habilitation character varying(20) NOT NULL,
    date_habilitation date,
    date_expiration date,
    habilitee_par_id bigint,
    motif_suspension text NOT NULL,
    CONSTRAINT organisation_suspension_avec_motif CHECK (((NOT ((statut_habilitation)::text = 'SUSPENDUE'::text)) OR (NOT (motif_suspension = ''::text))))
);


--
-- Name: accounts_organisation_secteurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_organisation_secteurs (
    id bigint NOT NULL,
    organisation_id bigint NOT NULL,
    secteur_id bigint NOT NULL
);


--
-- Name: accounts_organisation_domaines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_organisation_secteurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_organisation_domaines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_organisation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_organisation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_organisation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_servicemunicipal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_servicemunicipal (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    nom character varying(150) NOT NULL,
    description text NOT NULL,
    actif boolean NOT NULL,
    responsable_id bigint
);


--
-- Name: accounts_servicemunicipal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_servicemunicipal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_servicemunicipal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_utilisateur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_utilisateur (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    telephone character varying(128) NOT NULL,
    nom character varying(100) NOT NULL,
    prenoms character varying(150) NOT NULL,
    email character varying(254),
    role character varying(20) NOT NULL,
    telephone_verifie boolean NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    quartier_residence_id bigint,
    organisation_id bigint,
    service_id bigint,
    CONSTRAINT utilisateur_agent_avec_service CHECK (((NOT ((role)::text = 'AGENT'::text)) OR (service_id IS NOT NULL))),
    CONSTRAINT utilisateur_organisation_avec_organisation CHECK (((NOT ((role)::text = 'ORGANISATION'::text)) OR (organisation_id IS NOT NULL)))
);


--
-- Name: accounts_utilisateur_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_utilisateur_groups (
    id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: accounts_utilisateur_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_utilisateur_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_utilisateur_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_utilisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_utilisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_utilisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_utilisateur_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_utilisateur_user_permissions (
    id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: accounts_utilisateur_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_utilisateur_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_utilisateur_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: medias_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medias_media (
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    type character varying(10) NOT NULL,
    fichier character varying(255) NOT NULL,
    miniature character varying(255),
    mime_type character varying(100) NOT NULL,
    taille_octets integer NOT NULL,
    duree_secondes integer,
    largeur integer,
    hauteur integer,
    statut character varying(20) NOT NULL,
    auteur_id bigint NOT NULL,
    CONSTRAINT medias_media_duree_secondes_check CHECK ((duree_secondes >= 0)),
    CONSTRAINT medias_media_hauteur_check CHECK ((hauteur >= 0)),
    CONSTRAINT medias_media_largeur_check CHECK ((largeur >= 0)),
    CONSTRAINT medias_media_taille_octets_check CHECK ((taille_octets >= 0))
);


--
-- Name: notifications_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications_notification (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    type character varying(30) NOT NULL,
    titre character varying(150) NOT NULL,
    message text NOT NULL,
    cible_type character varying(20) NOT NULL,
    cible_id bigint NOT NULL,
    lu boolean NOT NULL,
    envoye_push boolean NOT NULL,
    destinataire_id bigint NOT NULL
);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: realisations_realisation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realisations_realisation (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    reference character varying(20) NOT NULL,
    titre character varying(200) NOT NULL,
    description text NOT NULL,
    statut character varying(20) NOT NULL,
    taux_avancement smallint NOT NULL,
    date_debut_prevue date,
    date_fin_prevue date,
    date_debut_reelle date,
    date_fin_reelle date,
    budget numeric(14,0),
    source_financement character varying(255) NOT NULL,
    prestataire character varying(255) NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6),
    publie boolean NOT NULL,
    cree_par_id bigint NOT NULL,
    secteur_id bigint NOT NULL,
    CONSTRAINT realisation_budget_positif CHECK (((budget IS NULL) OR (budget >= (0)::numeric))),
    CONSTRAINT realisation_dates_prevues_ordonnees CHECK (((date_debut_prevue IS NULL) OR (date_fin_prevue IS NULL) OR (date_fin_prevue >= date_debut_prevue))),
    CONSTRAINT realisation_dates_reelles_ordonnees CHECK (((date_debut_reelle IS NULL) OR (date_fin_reelle IS NULL) OR (date_fin_reelle >= date_debut_reelle))),
    CONSTRAINT realisation_position_complete CHECK ((((latitude IS NULL) AND (longitude IS NULL)) OR ((latitude IS NOT NULL) AND (longitude IS NOT NULL)))),
    CONSTRAINT realisation_taux_max_100 CHECK ((taux_avancement <= 100)),
    CONSTRAINT realisations_realisation_taux_avancement_check CHECK ((taux_avancement >= 0))
);


--
-- Name: realisations_realisation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.realisations_realisation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realisations_realisation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: realisations_realisation_quartiers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realisations_realisation_quartiers (
    id bigint NOT NULL,
    realisation_id bigint NOT NULL,
    quartier_id bigint NOT NULL
);


--
-- Name: realisations_realisation_quartiers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.realisations_realisation_quartiers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realisations_realisation_quartiers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: realisations_realisation_signalements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realisations_realisation_signalements (
    id bigint NOT NULL,
    realisation_id bigint NOT NULL,
    signalement_id bigint NOT NULL
);


--
-- Name: realisations_realisation_signalements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.realisations_realisation_signalements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realisations_realisation_signalements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: realisations_realisation_suggestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realisations_realisation_suggestions (
    id bigint NOT NULL,
    realisation_id bigint NOT NULL,
    suggestion_id bigint NOT NULL
);


--
-- Name: realisations_realisation_suggestions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.realisations_realisation_suggestions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realisations_realisation_suggestions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: realisations_realisationmedia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.realisations_realisationmedia (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    phase character varying(10) NOT NULL,
    legende character varying(255) NOT NULL,
    ordre smallint NOT NULL,
    media_id uuid NOT NULL,
    realisation_id bigint NOT NULL,
    CONSTRAINT realisations_realisationmedia_ordre_check CHECK ((ordre >= 0))
);


--
-- Name: realisations_realisationmedia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.realisations_realisationmedia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realisations_realisationmedia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: referentiel_secteur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referentiel_secteur (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    nom character varying(100) NOT NULL,
    code character varying(30) NOT NULL,
    description text NOT NULL,
    icone character varying(50) NOT NULL,
    couleur character varying(7) NOT NULL,
    pour_signalement boolean NOT NULL,
    pour_suggestion boolean NOT NULL,
    pour_realisation boolean NOT NULL,
    ordre smallint NOT NULL,
    actif boolean NOT NULL,
    service_par_defaut_id bigint,
    CONSTRAINT referentiel_categorie_ordre_check CHECK ((ordre >= 0))
);


--
-- Name: referentiel_categorie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.referentiel_secteur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.referentiel_categorie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: signalements_signalement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signalements_signalement (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    reference character varying(20) NOT NULL,
    titre character varying(150) NOT NULL,
    titre_genere boolean NOT NULL,
    description_texte text NOT NULL,
    anonyme boolean NOT NULL,
    mode_localisation character varying(10) NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6),
    precision_gps integer,
    repere character varying(255) NOT NULL,
    statut character varying(20) NOT NULL,
    priorite character varying(10) NOT NULL,
    date_resolution timestamp with time zone,
    agent_assigne_id bigint,
    auteur_id bigint NOT NULL,
    description_audio_id uuid,
    doublon_de_id bigint,
    quartier_id bigint NOT NULL,
    secteur_id bigint NOT NULL,
    service_assigne_id bigint,
    CONSTRAINT signalement_avec_description CHECK (((NOT (description_texte = ''::text)) OR (description_audio_id IS NOT NULL))),
    CONSTRAINT signalement_gps_complet CHECK (((NOT ((mode_localisation)::text = 'GPS'::text)) OR ((latitude IS NOT NULL) AND (longitude IS NOT NULL) AND (precision_gps IS NOT NULL)))),
    CONSTRAINT signalements_signalement_precision_gps_check CHECK ((precision_gps >= 0))
);


--
-- Name: signalements_signalement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.signalements_signalement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.signalements_signalement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: signalements_signalement_medias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signalements_signalement_medias (
    id bigint NOT NULL,
    signalement_id bigint NOT NULL,
    media_id uuid NOT NULL
);


--
-- Name: signalements_signalement_medias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.signalements_signalement_medias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.signalements_signalement_medias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: signalements_suivisignalement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signalements_suivisignalement (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    type_evenement character varying(20) NOT NULL,
    ancien_statut character varying(20) NOT NULL,
    nouveau_statut character varying(20) NOT NULL,
    commentaire text NOT NULL,
    visible_citoyen boolean NOT NULL,
    auteur_id bigint NOT NULL,
    signalement_id bigint NOT NULL,
    CONSTRAINT suivi_signalement_note_interne_invisible CHECK (((NOT ((type_evenement)::text = 'NOTE_INTERNE'::text)) OR (NOT visible_citoyen)))
);


--
-- Name: signalements_suivisignalement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.signalements_suivisignalement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.signalements_suivisignalement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suggestions_soutien; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suggestions_soutien (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    citoyen_id bigint NOT NULL,
    suggestion_id bigint NOT NULL
);


--
-- Name: suggestions_soutien_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suggestions_soutien ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suggestions_soutien_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suggestions_suggestion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suggestions_suggestion (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    reference character varying(20) NOT NULL,
    titre character varying(150) NOT NULL,
    description text NOT NULL,
    nb_soutiens integer NOT NULL,
    reponse_officielle text NOT NULL,
    repondu_le timestamp with time zone,
    auteur_id bigint NOT NULL,
    quartier_id bigint,
    repondu_par_id bigint,
    secteur_id bigint NOT NULL,
    est_pertinente boolean NOT NULL,
    CONSTRAINT suggestions_suggestion_nb_soutiens_check CHECK ((nb_soutiens >= 0))
);


--
-- Name: suggestions_suggestion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suggestions_suggestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suggestions_suggestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suggestions_suggestion_medias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suggestions_suggestion_medias (
    id bigint NOT NULL,
    suggestion_id bigint NOT NULL,
    media_id uuid NOT NULL
);


--
-- Name: suggestions_suggestion_medias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suggestions_suggestion_medias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suggestions_suggestion_medias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suggestions_suivisuggestion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suggestions_suivisuggestion (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    type_evenement character varying(20) NOT NULL,
    commentaire text NOT NULL,
    visible_citoyen boolean NOT NULL,
    auteur_id bigint NOT NULL,
    suggestion_id bigint NOT NULL,
    CONSTRAINT suivi_suggestion_note_interne_invisible CHECK (((NOT ((type_evenement)::text = 'NOTE_INTERNE'::text)) OR (NOT visible_citoyen)))
);


--
-- Name: suggestions_suivisuggestion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suggestions_suivisuggestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suggestions_suivisuggestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: territoire_arrondissement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.territoire_arrondissement (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    nom character varying(100) NOT NULL,
    code character varying(20) NOT NULL,
    commune_id bigint NOT NULL
);


--
-- Name: territoire_arrondissement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.territoire_arrondissement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.territoire_arrondissement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: territoire_commune; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.territoire_commune (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    nom character varying(100) NOT NULL,
    code character varying(20) NOT NULL,
    departement character varying(100) NOT NULL,
    lat_min numeric(9,6) NOT NULL,
    lat_max numeric(9,6) NOT NULL,
    lng_min numeric(9,6) NOT NULL,
    lng_max numeric(9,6) NOT NULL
);


--
-- Name: territoire_commune_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.territoire_commune ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.territoire_commune_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: territoire_quartier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.territoire_quartier (
    id bigint NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    maj_le timestamp with time zone NOT NULL,
    nom character varying(100) NOT NULL,
    code character varying(20) NOT NULL,
    latitude_centre numeric(9,6),
    longitude_centre numeric(9,6),
    actif boolean NOT NULL,
    arrondissement_id bigint NOT NULL
);


--
-- Name: territoire_quartier_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.territoire_quartier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.territoire_quartier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_appareil accounts_appareil_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_appareil
    ADD CONSTRAINT accounts_appareil_pkey PRIMARY KEY (id);


--
-- Name: accounts_appareil accounts_appareil_token_fcm_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_appareil
    ADD CONSTRAINT accounts_appareil_token_fcm_key UNIQUE (token_fcm);


--
-- Name: accounts_codeotp accounts_codeotp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_codeotp
    ADD CONSTRAINT accounts_codeotp_pkey PRIMARY KEY (id);


--
-- Name: accounts_organisation_secteurs accounts_organisation_do_organisation_id_categori_677afa10_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_organisation_secteurs
    ADD CONSTRAINT accounts_organisation_do_organisation_id_categori_677afa10_uniq UNIQUE (organisation_id, secteur_id);


--
-- Name: accounts_organisation_secteurs accounts_organisation_domaines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_organisation_secteurs
    ADD CONSTRAINT accounts_organisation_domaines_pkey PRIMARY KEY (id);


--
-- Name: accounts_organisation accounts_organisation_numero_enregistrement_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_organisation
    ADD CONSTRAINT accounts_organisation_numero_enregistrement_key UNIQUE (numero_enregistrement);


--
-- Name: accounts_organisation accounts_organisation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_organisation
    ADD CONSTRAINT accounts_organisation_pkey PRIMARY KEY (id);


--
-- Name: accounts_servicemunicipal accounts_servicemunicipal_nom_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_servicemunicipal
    ADD CONSTRAINT accounts_servicemunicipal_nom_key UNIQUE (nom);


--
-- Name: accounts_servicemunicipal accounts_servicemunicipal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_servicemunicipal
    ADD CONSTRAINT accounts_servicemunicipal_pkey PRIMARY KEY (id);


--
-- Name: accounts_utilisateur_groups accounts_utilisateur_gro_utilisateur_id_group_id_941da25f_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur_groups
    ADD CONSTRAINT accounts_utilisateur_gro_utilisateur_id_group_id_941da25f_uniq UNIQUE (utilisateur_id, group_id);


--
-- Name: accounts_utilisateur_groups accounts_utilisateur_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur_groups
    ADD CONSTRAINT accounts_utilisateur_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_utilisateur accounts_utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur
    ADD CONSTRAINT accounts_utilisateur_pkey PRIMARY KEY (id);


--
-- Name: accounts_utilisateur accounts_utilisateur_telephone_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur
    ADD CONSTRAINT accounts_utilisateur_telephone_key UNIQUE (telephone);


--
-- Name: accounts_utilisateur_user_permissions accounts_utilisateur_use_utilisateur_id_permissio_59447ab2_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur_user_permissions
    ADD CONSTRAINT accounts_utilisateur_use_utilisateur_id_permissio_59447ab2_uniq UNIQUE (utilisateur_id, permission_id);


--
-- Name: accounts_utilisateur_user_permissions accounts_utilisateur_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur_user_permissions
    ADD CONSTRAINT accounts_utilisateur_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: territoire_arrondissement arrondissement_unique_par_commune; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territoire_arrondissement
    ADD CONSTRAINT arrondissement_unique_par_commune UNIQUE (commune_id, nom);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: medias_media medias_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medias_media
    ADD CONSTRAINT medias_media_pkey PRIMARY KEY (id);


--
-- Name: notifications_notification notifications_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_pkey PRIMARY KEY (id);


--
-- Name: territoire_quartier quartier_unique_par_arrondissement; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territoire_quartier
    ADD CONSTRAINT quartier_unique_par_arrondissement UNIQUE (arrondissement_id, nom);


--
-- Name: realisations_realisation realisations_realisation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation
    ADD CONSTRAINT realisations_realisation_pkey PRIMARY KEY (id);


--
-- Name: realisations_realisation_quartiers realisations_realisation_quartiers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_quartiers
    ADD CONSTRAINT realisations_realisation_quartiers_pkey PRIMARY KEY (id);


--
-- Name: realisations_realisation_quartiers realisations_realisation_realisation_id_quartier__9b1b4ab5_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_quartiers
    ADD CONSTRAINT realisations_realisation_realisation_id_quartier__9b1b4ab5_uniq UNIQUE (realisation_id, quartier_id);


--
-- Name: realisations_realisation_signalements realisations_realisation_realisation_id_signaleme_8fe3e6d4_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_signalements
    ADD CONSTRAINT realisations_realisation_realisation_id_signaleme_8fe3e6d4_uniq UNIQUE (realisation_id, signalement_id);


--
-- Name: realisations_realisation_suggestions realisations_realisation_realisation_id_suggestio_dc7ca7ef_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_suggestions
    ADD CONSTRAINT realisations_realisation_realisation_id_suggestio_dc7ca7ef_uniq UNIQUE (realisation_id, suggestion_id);


--
-- Name: realisations_realisation realisations_realisation_reference_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation
    ADD CONSTRAINT realisations_realisation_reference_key UNIQUE (reference);


--
-- Name: realisations_realisation_signalements realisations_realisation_signalements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_signalements
    ADD CONSTRAINT realisations_realisation_signalements_pkey PRIMARY KEY (id);


--
-- Name: realisations_realisation_suggestions realisations_realisation_suggestions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_suggestions
    ADD CONSTRAINT realisations_realisation_suggestions_pkey PRIMARY KEY (id);


--
-- Name: realisations_realisationmedia realisations_realisationmedia_media_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisationmedia
    ADD CONSTRAINT realisations_realisationmedia_media_id_key UNIQUE (media_id);


--
-- Name: realisations_realisationmedia realisations_realisationmedia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisationmedia
    ADD CONSTRAINT realisations_realisationmedia_pkey PRIMARY KEY (id);


--
-- Name: referentiel_secteur referentiel_categorie_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referentiel_secteur
    ADD CONSTRAINT referentiel_categorie_code_key UNIQUE (code);


--
-- Name: referentiel_secteur referentiel_categorie_nom_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referentiel_secteur
    ADD CONSTRAINT referentiel_categorie_nom_key UNIQUE (nom);


--
-- Name: referentiel_secteur referentiel_categorie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referentiel_secteur
    ADD CONSTRAINT referentiel_categorie_pkey PRIMARY KEY (id);


--
-- Name: signalements_signalement signalements_signalement_description_audio_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signalement_description_audio_id_key UNIQUE (description_audio_id);


--
-- Name: signalements_signalement_medias signalements_signalement_medias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement_medias
    ADD CONSTRAINT signalements_signalement_medias_pkey PRIMARY KEY (id);


--
-- Name: signalements_signalement signalements_signalement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signalement_pkey PRIMARY KEY (id);


--
-- Name: signalements_signalement signalements_signalement_reference_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signalement_reference_key UNIQUE (reference);


--
-- Name: signalements_signalement_medias signalements_signalement_signalement_id_media_id_ae663553_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement_medias
    ADD CONSTRAINT signalements_signalement_signalement_id_media_id_ae663553_uniq UNIQUE (signalement_id, media_id);


--
-- Name: signalements_suivisignalement signalements_suivisignalement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_suivisignalement
    ADD CONSTRAINT signalements_suivisignalement_pkey PRIMARY KEY (id);


--
-- Name: suggestions_soutien soutien_unique_par_citoyen; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_soutien
    ADD CONSTRAINT soutien_unique_par_citoyen UNIQUE (suggestion_id, citoyen_id);


--
-- Name: suggestions_soutien suggestions_soutien_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_soutien
    ADD CONSTRAINT suggestions_soutien_pkey PRIMARY KEY (id);


--
-- Name: suggestions_suggestion_medias suggestions_suggestion_m_suggestion_id_media_id_30257182_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion_medias
    ADD CONSTRAINT suggestions_suggestion_m_suggestion_id_media_id_30257182_uniq UNIQUE (suggestion_id, media_id);


--
-- Name: suggestions_suggestion_medias suggestions_suggestion_medias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion_medias
    ADD CONSTRAINT suggestions_suggestion_medias_pkey PRIMARY KEY (id);


--
-- Name: suggestions_suggestion suggestions_suggestion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion
    ADD CONSTRAINT suggestions_suggestion_pkey PRIMARY KEY (id);


--
-- Name: suggestions_suggestion suggestions_suggestion_reference_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion
    ADD CONSTRAINT suggestions_suggestion_reference_key UNIQUE (reference);


--
-- Name: suggestions_suivisuggestion suggestions_suivisuggestion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suivisuggestion
    ADD CONSTRAINT suggestions_suivisuggestion_pkey PRIMARY KEY (id);


--
-- Name: territoire_arrondissement territoire_arrondissement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territoire_arrondissement
    ADD CONSTRAINT territoire_arrondissement_pkey PRIMARY KEY (id);


--
-- Name: territoire_commune territoire_commune_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territoire_commune
    ADD CONSTRAINT territoire_commune_code_key UNIQUE (code);


--
-- Name: territoire_commune territoire_commune_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territoire_commune
    ADD CONSTRAINT territoire_commune_pkey PRIMARY KEY (id);


--
-- Name: territoire_quartier territoire_quartier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territoire_quartier
    ADD CONSTRAINT territoire_quartier_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: accounts_appareil_cree_le_a2425686; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_appareil_cree_le_a2425686 ON public.accounts_appareil USING btree (cree_le);


--
-- Name: accounts_appareil_token_fcm_139cb72f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_appareil_token_fcm_139cb72f_like ON public.accounts_appareil USING btree (token_fcm varchar_pattern_ops);


--
-- Name: accounts_appareil_utilisateur_id_3ee292d8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_appareil_utilisateur_id_3ee292d8 ON public.accounts_appareil USING btree (utilisateur_id);


--
-- Name: accounts_co_utilisa_3a8f9c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_co_utilisa_3a8f9c_idx ON public.accounts_codeotp USING btree (utilisateur_id, motif);


--
-- Name: accounts_codeotp_cree_le_f61f8cf3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_codeotp_cree_le_f61f8cf3 ON public.accounts_codeotp USING btree (cree_le);


--
-- Name: accounts_codeotp_utilisateur_id_bb985052; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_codeotp_utilisateur_id_bb985052 ON public.accounts_codeotp USING btree (utilisateur_id);


--
-- Name: accounts_organisation_cree_le_94f09f09; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_organisation_cree_le_94f09f09 ON public.accounts_organisation USING btree (cree_le);


--
-- Name: accounts_organisation_domaines_categorie_id_a7c909b1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_organisation_domaines_categorie_id_a7c909b1 ON public.accounts_organisation_secteurs USING btree (secteur_id);


--
-- Name: accounts_organisation_domaines_organisation_id_5f01413c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_organisation_domaines_organisation_id_5f01413c ON public.accounts_organisation_secteurs USING btree (organisation_id);


--
-- Name: accounts_organisation_habilitee_par_id_bed29c29; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_organisation_habilitee_par_id_bed29c29 ON public.accounts_organisation USING btree (habilitee_par_id);


--
-- Name: accounts_organisation_numero_enregistrement_6a73c259_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_organisation_numero_enregistrement_6a73c259_like ON public.accounts_organisation USING btree (numero_enregistrement varchar_pattern_ops);


--
-- Name: accounts_servicemunicipal_cree_le_354154ae; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_servicemunicipal_cree_le_354154ae ON public.accounts_servicemunicipal USING btree (cree_le);


--
-- Name: accounts_servicemunicipal_nom_93fec51d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_servicemunicipal_nom_93fec51d_like ON public.accounts_servicemunicipal USING btree (nom varchar_pattern_ops);


--
-- Name: accounts_servicemunicipal_responsable_id_c54e6fb1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_servicemunicipal_responsable_id_c54e6fb1 ON public.accounts_servicemunicipal USING btree (responsable_id);


--
-- Name: accounts_utilisateur_cree_le_86d82a1a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_utilisateur_cree_le_86d82a1a ON public.accounts_utilisateur USING btree (cree_le);


--
-- Name: accounts_utilisateur_groups_group_id_a4007cd2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_utilisateur_groups_group_id_a4007cd2 ON public.accounts_utilisateur_groups USING btree (group_id);


--
-- Name: accounts_utilisateur_groups_utilisateur_id_ca92c3d8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_utilisateur_groups_utilisateur_id_ca92c3d8 ON public.accounts_utilisateur_groups USING btree (utilisateur_id);


--
-- Name: accounts_utilisateur_organisation_id_abeb200d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_utilisateur_organisation_id_abeb200d ON public.accounts_utilisateur USING btree (organisation_id);


--
-- Name: accounts_utilisateur_quartier_residence_id_d4dae1dd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_utilisateur_quartier_residence_id_d4dae1dd ON public.accounts_utilisateur USING btree (quartier_residence_id);


--
-- Name: accounts_utilisateur_service_id_8f839e8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_utilisateur_service_id_8f839e8b ON public.accounts_utilisateur USING btree (service_id);


--
-- Name: accounts_utilisateur_telephone_61535039_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_utilisateur_telephone_61535039_like ON public.accounts_utilisateur USING btree (telephone varchar_pattern_ops);


--
-- Name: accounts_utilisateur_user_permissions_permission_id_6f24b1cb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_utilisateur_user_permissions_permission_id_6f24b1cb ON public.accounts_utilisateur_user_permissions USING btree (permission_id);


--
-- Name: accounts_utilisateur_user_permissions_utilisateur_id_1f62d6d5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_utilisateur_user_permissions_utilisateur_id_1f62d6d5 ON public.accounts_utilisateur_user_permissions USING btree (utilisateur_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: media_statut_cree_le_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX media_statut_cree_le_idx ON public.medias_media USING btree (statut, cree_le);


--
-- Name: medias_media_auteur_id_c2e5a453; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX medias_media_auteur_id_c2e5a453 ON public.medias_media USING btree (auteur_id);


--
-- Name: medias_media_cree_le_14a5cd50; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX medias_media_cree_le_14a5cd50 ON public.medias_media USING btree (cree_le);


--
-- Name: notification_destinataire_lu; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notification_destinataire_lu ON public.notifications_notification USING btree (destinataire_id, lu);


--
-- Name: notifications_notification_cree_le_ee1d45f6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_notification_cree_le_ee1d45f6 ON public.notifications_notification USING btree (cree_le);


--
-- Name: notifications_notification_destinataire_id_04593f78; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_notification_destinataire_id_04593f78 ON public.notifications_notification USING btree (destinataire_id);


--
-- Name: realisation_publie_statut_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisation_publie_statut_idx ON public.realisations_realisation USING btree (publie, statut);


--
-- Name: realisations_realisation_cree_le_e7ff4ab5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_cree_le_e7ff4ab5 ON public.realisations_realisation USING btree (cree_le);


--
-- Name: realisations_realisation_cree_par_id_11d6b9eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_cree_par_id_11d6b9eb ON public.realisations_realisation USING btree (cree_par_id);


--
-- Name: realisations_realisation_quartiers_quartier_id_f21e59db; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_quartiers_quartier_id_f21e59db ON public.realisations_realisation_quartiers USING btree (quartier_id);


--
-- Name: realisations_realisation_quartiers_realisation_id_c9a9f187; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_quartiers_realisation_id_c9a9f187 ON public.realisations_realisation_quartiers USING btree (realisation_id);


--
-- Name: realisations_realisation_reference_3cbabb0e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_reference_3cbabb0e_like ON public.realisations_realisation USING btree (reference varchar_pattern_ops);


--
-- Name: realisations_realisation_secteur_id_a97e4c37; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_secteur_id_a97e4c37 ON public.realisations_realisation USING btree (secteur_id);


--
-- Name: realisations_realisation_signalements_realisation_id_99252a9a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_signalements_realisation_id_99252a9a ON public.realisations_realisation_signalements USING btree (realisation_id);


--
-- Name: realisations_realisation_signalements_signalement_id_29ebc781; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_signalements_signalement_id_29ebc781 ON public.realisations_realisation_signalements USING btree (signalement_id);


--
-- Name: realisations_realisation_suggestions_realisation_id_ef5f416c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_suggestions_realisation_id_ef5f416c ON public.realisations_realisation_suggestions USING btree (realisation_id);


--
-- Name: realisations_realisation_suggestions_suggestion_id_477f642e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisation_suggestions_suggestion_id_477f642e ON public.realisations_realisation_suggestions USING btree (suggestion_id);


--
-- Name: realisations_realisationmedia_cree_le_360a4406; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisationmedia_cree_le_360a4406 ON public.realisations_realisationmedia USING btree (cree_le);


--
-- Name: realisations_realisationmedia_realisation_id_1643c2a9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX realisations_realisationmedia_realisation_id_1643c2a9 ON public.realisations_realisationmedia USING btree (realisation_id);


--
-- Name: referentiel_categorie_code_dd5c8472_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX referentiel_categorie_code_dd5c8472_like ON public.referentiel_secteur USING btree (code varchar_pattern_ops);


--
-- Name: referentiel_categorie_cree_le_ff2425bb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX referentiel_categorie_cree_le_ff2425bb ON public.referentiel_secteur USING btree (cree_le);


--
-- Name: referentiel_categorie_nom_3a7963a1_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX referentiel_categorie_nom_3a7963a1_like ON public.referentiel_secteur USING btree (nom varchar_pattern_ops);


--
-- Name: referentiel_categorie_service_par_defaut_id_2f7b85f2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX referentiel_categorie_service_par_defaut_id_2f7b85f2 ON public.referentiel_secteur USING btree (service_par_defaut_id);


--
-- Name: signalement_statut_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalement_statut_idx ON public.signalements_signalement USING btree (statut);


--
-- Name: signalements_signalement_agent_assigne_id_d3e3a191; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_agent_assigne_id_d3e3a191 ON public.signalements_signalement USING btree (agent_assigne_id);


--
-- Name: signalements_signalement_auteur_id_31fca6de; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_auteur_id_31fca6de ON public.signalements_signalement USING btree (auteur_id);


--
-- Name: signalements_signalement_cree_le_0d933ce5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_cree_le_0d933ce5 ON public.signalements_signalement USING btree (cree_le);


--
-- Name: signalements_signalement_doublon_de_id_caf340e9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_doublon_de_id_caf340e9 ON public.signalements_signalement USING btree (doublon_de_id);


--
-- Name: signalements_signalement_medias_media_id_731d0fc2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_medias_media_id_731d0fc2 ON public.signalements_signalement_medias USING btree (media_id);


--
-- Name: signalements_signalement_medias_signalement_id_c6ee8005; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_medias_signalement_id_c6ee8005 ON public.signalements_signalement_medias USING btree (signalement_id);


--
-- Name: signalements_signalement_quartier_id_48081097; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_quartier_id_48081097 ON public.signalements_signalement USING btree (quartier_id);


--
-- Name: signalements_signalement_reference_5a053f17_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_reference_5a053f17_like ON public.signalements_signalement USING btree (reference varchar_pattern_ops);


--
-- Name: signalements_signalement_secteur_id_308f1699; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_secteur_id_308f1699 ON public.signalements_signalement USING btree (secteur_id);


--
-- Name: signalements_signalement_service_assigne_id_071a7cbd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_signalement_service_assigne_id_071a7cbd ON public.signalements_signalement USING btree (service_assigne_id);


--
-- Name: signalements_suivisignalement_auteur_id_e6ff7df5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_suivisignalement_auteur_id_e6ff7df5 ON public.signalements_suivisignalement USING btree (auteur_id);


--
-- Name: signalements_suivisignalement_cree_le_387fd2ae; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_suivisignalement_cree_le_387fd2ae ON public.signalements_suivisignalement USING btree (cree_le);


--
-- Name: signalements_suivisignalement_signalement_id_a07d4c38; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signalements_suivisignalement_signalement_id_a07d4c38 ON public.signalements_suivisignalement USING btree (signalement_id);


--
-- Name: suggestions_soutien_citoyen_id_0a52c171; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_soutien_citoyen_id_0a52c171 ON public.suggestions_soutien USING btree (citoyen_id);


--
-- Name: suggestions_soutien_cree_le_8309c8f8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_soutien_cree_le_8309c8f8 ON public.suggestions_soutien USING btree (cree_le);


--
-- Name: suggestions_soutien_suggestion_id_b9c6123c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_soutien_suggestion_id_b9c6123c ON public.suggestions_soutien USING btree (suggestion_id);


--
-- Name: suggestions_suggestion_auteur_id_5cf3328d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suggestion_auteur_id_5cf3328d ON public.suggestions_suggestion USING btree (auteur_id);


--
-- Name: suggestions_suggestion_cree_le_943dc5ff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suggestion_cree_le_943dc5ff ON public.suggestions_suggestion USING btree (cree_le);


--
-- Name: suggestions_suggestion_est_pertinente_bd5565e7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suggestion_est_pertinente_bd5565e7 ON public.suggestions_suggestion USING btree (est_pertinente);


--
-- Name: suggestions_suggestion_medias_media_id_c1fa01ba; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suggestion_medias_media_id_c1fa01ba ON public.suggestions_suggestion_medias USING btree (media_id);


--
-- Name: suggestions_suggestion_medias_suggestion_id_c272273e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suggestion_medias_suggestion_id_c272273e ON public.suggestions_suggestion_medias USING btree (suggestion_id);


--
-- Name: suggestions_suggestion_quartier_id_cc7580a8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suggestion_quartier_id_cc7580a8 ON public.suggestions_suggestion USING btree (quartier_id);


--
-- Name: suggestions_suggestion_reference_3b23a10a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suggestion_reference_3b23a10a_like ON public.suggestions_suggestion USING btree (reference varchar_pattern_ops);


--
-- Name: suggestions_suggestion_repondu_par_id_4d18ba00; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suggestion_repondu_par_id_4d18ba00 ON public.suggestions_suggestion USING btree (repondu_par_id);


--
-- Name: suggestions_suggestion_secteur_id_a74ff557; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suggestion_secteur_id_a74ff557 ON public.suggestions_suggestion USING btree (secteur_id);


--
-- Name: suggestions_suivisuggestion_auteur_id_ee8a085d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suivisuggestion_auteur_id_ee8a085d ON public.suggestions_suivisuggestion USING btree (auteur_id);


--
-- Name: suggestions_suivisuggestion_cree_le_2a4b8cde; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suivisuggestion_cree_le_2a4b8cde ON public.suggestions_suivisuggestion USING btree (cree_le);


--
-- Name: suggestions_suivisuggestion_suggestion_id_3031c17f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suggestions_suivisuggestion_suggestion_id_3031c17f ON public.suggestions_suivisuggestion USING btree (suggestion_id);


--
-- Name: territoire_arrondissement_commune_id_b02e9f9b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX territoire_arrondissement_commune_id_b02e9f9b ON public.territoire_arrondissement USING btree (commune_id);


--
-- Name: territoire_arrondissement_cree_le_842b664f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX territoire_arrondissement_cree_le_842b664f ON public.territoire_arrondissement USING btree (cree_le);


--
-- Name: territoire_commune_code_dbdcd642_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX territoire_commune_code_dbdcd642_like ON public.territoire_commune USING btree (code varchar_pattern_ops);


--
-- Name: territoire_commune_cree_le_ea58ac44; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX territoire_commune_cree_le_ea58ac44 ON public.territoire_commune USING btree (cree_le);


--
-- Name: territoire_quartier_arrondissement_id_422ac228; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX territoire_quartier_arrondissement_id_422ac228 ON public.territoire_quartier USING btree (arrondissement_id);


--
-- Name: territoire_quartier_cree_le_4b627145; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX territoire_quartier_cree_le_4b627145 ON public.territoire_quartier USING btree (cree_le);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: accounts_appareil accounts_appareil_utilisateur_id_3ee292d8_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_appareil
    ADD CONSTRAINT accounts_appareil_utilisateur_id_3ee292d8_fk_accounts_ FOREIGN KEY (utilisateur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_codeotp accounts_codeotp_utilisateur_id_bb985052_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_codeotp
    ADD CONSTRAINT accounts_codeotp_utilisateur_id_bb985052_fk_accounts_ FOREIGN KEY (utilisateur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_organisation accounts_organisatio_habilitee_par_id_bed29c29_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_organisation
    ADD CONSTRAINT accounts_organisatio_habilitee_par_id_bed29c29_fk_accounts_ FOREIGN KEY (habilitee_par_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_organisation_secteurs accounts_organisatio_organisation_id_5f01413c_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_organisation_secteurs
    ADD CONSTRAINT accounts_organisatio_organisation_id_5f01413c_fk_accounts_ FOREIGN KEY (organisation_id) REFERENCES public.accounts_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_organisation_secteurs accounts_organisatio_secteur_id_3238bfad_fk_referenti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_organisation_secteurs
    ADD CONSTRAINT accounts_organisatio_secteur_id_3238bfad_fk_referenti FOREIGN KEY (secteur_id) REFERENCES public.referentiel_secteur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_servicemunicipal accounts_servicemuni_responsable_id_c54e6fb1_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_servicemunicipal
    ADD CONSTRAINT accounts_servicemuni_responsable_id_c54e6fb1_fk_accounts_ FOREIGN KEY (responsable_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur_groups accounts_utilisateur_groups_group_id_a4007cd2_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur_groups
    ADD CONSTRAINT accounts_utilisateur_groups_group_id_a4007cd2_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur accounts_utilisateur_organisation_id_abeb200d_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur
    ADD CONSTRAINT accounts_utilisateur_organisation_id_abeb200d_fk_accounts_ FOREIGN KEY (organisation_id) REFERENCES public.accounts_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur_user_permissions accounts_utilisateur_permission_id_6f24b1cb_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur_user_permissions
    ADD CONSTRAINT accounts_utilisateur_permission_id_6f24b1cb_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur accounts_utilisateur_quartier_residence_i_d4dae1dd_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur
    ADD CONSTRAINT accounts_utilisateur_quartier_residence_i_d4dae1dd_fk_territoir FOREIGN KEY (quartier_residence_id) REFERENCES public.territoire_quartier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur accounts_utilisateur_service_id_8f839e8b_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur
    ADD CONSTRAINT accounts_utilisateur_service_id_8f839e8b_fk_accounts_ FOREIGN KEY (service_id) REFERENCES public.accounts_servicemunicipal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur_user_permissions accounts_utilisateur_utilisateur_id_1f62d6d5_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur_user_permissions
    ADD CONSTRAINT accounts_utilisateur_utilisateur_id_1f62d6d5_fk_accounts_ FOREIGN KEY (utilisateur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_utilisateur_groups accounts_utilisateur_utilisateur_id_ca92c3d8_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_utilisateur_groups
    ADD CONSTRAINT accounts_utilisateur_utilisateur_id_ca92c3d8_fk_accounts_ FOREIGN KEY (utilisateur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_utilisateur_id FOREIGN KEY (user_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: medias_media medias_media_auteur_id_c2e5a453_fk_accounts_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medias_media
    ADD CONSTRAINT medias_media_auteur_id_c2e5a453_fk_accounts_utilisateur_id FOREIGN KEY (auteur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notifi_destinataire_id_04593f78_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notifi_destinataire_id_04593f78_fk_accounts_ FOREIGN KEY (destinataire_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisation realisations_realisa_cree_par_id_11d6b9eb_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation
    ADD CONSTRAINT realisations_realisa_cree_par_id_11d6b9eb_fk_accounts_ FOREIGN KEY (cree_par_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisationmedia realisations_realisa_media_id_0ce5564f_fk_medias_me; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisationmedia
    ADD CONSTRAINT realisations_realisa_media_id_0ce5564f_fk_medias_me FOREIGN KEY (media_id) REFERENCES public.medias_media(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisation_quartiers realisations_realisa_quartier_id_f21e59db_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_quartiers
    ADD CONSTRAINT realisations_realisa_quartier_id_f21e59db_fk_territoir FOREIGN KEY (quartier_id) REFERENCES public.territoire_quartier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisationmedia realisations_realisa_realisation_id_1643c2a9_fk_realisati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisationmedia
    ADD CONSTRAINT realisations_realisa_realisation_id_1643c2a9_fk_realisati FOREIGN KEY (realisation_id) REFERENCES public.realisations_realisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisation_signalements realisations_realisa_realisation_id_99252a9a_fk_realisati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_signalements
    ADD CONSTRAINT realisations_realisa_realisation_id_99252a9a_fk_realisati FOREIGN KEY (realisation_id) REFERENCES public.realisations_realisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisation_quartiers realisations_realisa_realisation_id_c9a9f187_fk_realisati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_quartiers
    ADD CONSTRAINT realisations_realisa_realisation_id_c9a9f187_fk_realisati FOREIGN KEY (realisation_id) REFERENCES public.realisations_realisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisation_suggestions realisations_realisa_realisation_id_ef5f416c_fk_realisati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_suggestions
    ADD CONSTRAINT realisations_realisa_realisation_id_ef5f416c_fk_realisati FOREIGN KEY (realisation_id) REFERENCES public.realisations_realisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisation realisations_realisa_secteur_id_a97e4c37_fk_referenti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation
    ADD CONSTRAINT realisations_realisa_secteur_id_a97e4c37_fk_referenti FOREIGN KEY (secteur_id) REFERENCES public.referentiel_secteur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisation_signalements realisations_realisa_signalement_id_29ebc781_fk_signaleme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_signalements
    ADD CONSTRAINT realisations_realisa_signalement_id_29ebc781_fk_signaleme FOREIGN KEY (signalement_id) REFERENCES public.signalements_signalement(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: realisations_realisation_suggestions realisations_realisa_suggestion_id_477f642e_fk_suggestio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.realisations_realisation_suggestions
    ADD CONSTRAINT realisations_realisa_suggestion_id_477f642e_fk_suggestio FOREIGN KEY (suggestion_id) REFERENCES public.suggestions_suggestion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: referentiel_secteur referentiel_categori_service_par_defaut_i_2f7b85f2_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referentiel_secteur
    ADD CONSTRAINT referentiel_categori_service_par_defaut_i_2f7b85f2_fk_accounts_ FOREIGN KEY (service_par_defaut_id) REFERENCES public.accounts_servicemunicipal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_signalement signalements_signale_agent_assigne_id_d3e3a191_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signale_agent_assigne_id_d3e3a191_fk_accounts_ FOREIGN KEY (agent_assigne_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_signalement signalements_signale_auteur_id_31fca6de_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signale_auteur_id_31fca6de_fk_accounts_ FOREIGN KEY (auteur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_signalement signalements_signale_description_audio_id_eb05453c_fk_medias_me; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signale_description_audio_id_eb05453c_fk_medias_me FOREIGN KEY (description_audio_id) REFERENCES public.medias_media(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_signalement signalements_signale_doublon_de_id_caf340e9_fk_signaleme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signale_doublon_de_id_caf340e9_fk_signaleme FOREIGN KEY (doublon_de_id) REFERENCES public.signalements_signalement(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_signalement_medias signalements_signale_media_id_731d0fc2_fk_medias_me; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement_medias
    ADD CONSTRAINT signalements_signale_media_id_731d0fc2_fk_medias_me FOREIGN KEY (media_id) REFERENCES public.medias_media(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_signalement signalements_signale_quartier_id_48081097_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signale_quartier_id_48081097_fk_territoir FOREIGN KEY (quartier_id) REFERENCES public.territoire_quartier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_signalement signalements_signale_secteur_id_308f1699_fk_referenti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signale_secteur_id_308f1699_fk_referenti FOREIGN KEY (secteur_id) REFERENCES public.referentiel_secteur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_signalement signalements_signale_service_assigne_id_071a7cbd_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement
    ADD CONSTRAINT signalements_signale_service_assigne_id_071a7cbd_fk_accounts_ FOREIGN KEY (service_assigne_id) REFERENCES public.accounts_servicemunicipal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_signalement_medias signalements_signale_signalement_id_c6ee8005_fk_signaleme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_signalement_medias
    ADD CONSTRAINT signalements_signale_signalement_id_c6ee8005_fk_signaleme FOREIGN KEY (signalement_id) REFERENCES public.signalements_signalement(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_suivisignalement signalements_suivisi_auteur_id_e6ff7df5_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_suivisignalement
    ADD CONSTRAINT signalements_suivisi_auteur_id_e6ff7df5_fk_accounts_ FOREIGN KEY (auteur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: signalements_suivisignalement signalements_suivisi_signalement_id_a07d4c38_fk_signaleme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signalements_suivisignalement
    ADD CONSTRAINT signalements_suivisi_signalement_id_a07d4c38_fk_signaleme FOREIGN KEY (signalement_id) REFERENCES public.signalements_signalement(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_soutien suggestions_soutien_citoyen_id_0a52c171_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_soutien
    ADD CONSTRAINT suggestions_soutien_citoyen_id_0a52c171_fk_accounts_ FOREIGN KEY (citoyen_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_soutien suggestions_soutien_suggestion_id_b9c6123c_fk_suggestio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_soutien
    ADD CONSTRAINT suggestions_soutien_suggestion_id_b9c6123c_fk_suggestio FOREIGN KEY (suggestion_id) REFERENCES public.suggestions_suggestion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_suggestion suggestions_suggesti_auteur_id_5cf3328d_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion
    ADD CONSTRAINT suggestions_suggesti_auteur_id_5cf3328d_fk_accounts_ FOREIGN KEY (auteur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_suggestion_medias suggestions_suggesti_media_id_c1fa01ba_fk_medias_me; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion_medias
    ADD CONSTRAINT suggestions_suggesti_media_id_c1fa01ba_fk_medias_me FOREIGN KEY (media_id) REFERENCES public.medias_media(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_suggestion suggestions_suggesti_quartier_id_cc7580a8_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion
    ADD CONSTRAINT suggestions_suggesti_quartier_id_cc7580a8_fk_territoir FOREIGN KEY (quartier_id) REFERENCES public.territoire_quartier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_suggestion suggestions_suggesti_repondu_par_id_4d18ba00_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion
    ADD CONSTRAINT suggestions_suggesti_repondu_par_id_4d18ba00_fk_accounts_ FOREIGN KEY (repondu_par_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_suggestion suggestions_suggesti_secteur_id_a74ff557_fk_referenti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion
    ADD CONSTRAINT suggestions_suggesti_secteur_id_a74ff557_fk_referenti FOREIGN KEY (secteur_id) REFERENCES public.referentiel_secteur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_suggestion_medias suggestions_suggesti_suggestion_id_c272273e_fk_suggestio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suggestion_medias
    ADD CONSTRAINT suggestions_suggesti_suggestion_id_c272273e_fk_suggestio FOREIGN KEY (suggestion_id) REFERENCES public.suggestions_suggestion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_suivisuggestion suggestions_suivisug_auteur_id_ee8a085d_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suivisuggestion
    ADD CONSTRAINT suggestions_suivisug_auteur_id_ee8a085d_fk_accounts_ FOREIGN KEY (auteur_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suggestions_suivisuggestion suggestions_suivisug_suggestion_id_3031c17f_fk_suggestio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suggestions_suivisuggestion
    ADD CONSTRAINT suggestions_suivisug_suggestion_id_3031c17f_fk_suggestio FOREIGN KEY (suggestion_id) REFERENCES public.suggestions_suggestion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: territoire_arrondissement territoire_arrondiss_commune_id_b02e9f9b_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territoire_arrondissement
    ADD CONSTRAINT territoire_arrondiss_commune_id_b02e9f9b_fk_territoir FOREIGN KEY (commune_id) REFERENCES public.territoire_commune(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: territoire_quartier territoire_quartier_arrondissement_id_422ac228_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territoire_quartier
    ADD CONSTRAINT territoire_quartier_arrondissement_id_422ac228_fk_territoir FOREIGN KEY (arrondissement_id) REFERENCES public.territoire_arrondissement(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict x2UuphhWyfAMBqV4wGCs6becaC5JJHP1X8ht59lNO7FKeZaQoJcUTtss7LhNWuo


-- Historique des migrations appliquées
--
-- PostgreSQL database dump
--

\restrict t3hA2CJxLwPvbrYoeLCUdzHtk4blY2HFUakTvthELNpjUo9c5I4g0zXbGQHuu9D

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.django_migrations VALUES (1, 'territoire', '0001_initial', '2026-10-06 14:39:56.22522+00');
INSERT INTO public.django_migrations VALUES (2, 'contenttypes', '0001_initial', '2026-10-06 14:39:56.232798+00');
INSERT INTO public.django_migrations VALUES (3, 'contenttypes', '0002_remove_content_type_name', '2026-10-06 14:39:56.248275+00');
INSERT INTO public.django_migrations VALUES (4, 'auth', '0001_initial', '2026-10-06 14:39:56.281034+00');
INSERT INTO public.django_migrations VALUES (5, 'auth', '0002_alter_permission_name_max_length', '2026-10-06 14:39:56.287703+00');
INSERT INTO public.django_migrations VALUES (6, 'auth', '0003_alter_user_email_max_length', '2026-10-06 14:39:56.299478+00');
INSERT INTO public.django_migrations VALUES (7, 'auth', '0004_alter_user_username_opts', '2026-10-06 14:39:56.310857+00');
INSERT INTO public.django_migrations VALUES (8, 'auth', '0005_alter_user_last_login_null', '2026-10-06 14:39:56.31977+00');
INSERT INTO public.django_migrations VALUES (9, 'auth', '0006_require_contenttypes_0002', '2026-10-06 14:39:56.324583+00');
INSERT INTO public.django_migrations VALUES (10, 'auth', '0007_alter_validators_add_error_messages', '2026-10-06 14:39:56.331143+00');
INSERT INTO public.django_migrations VALUES (11, 'auth', '0008_alter_user_username_max_length', '2026-10-06 14:39:56.3377+00');
INSERT INTO public.django_migrations VALUES (12, 'auth', '0009_alter_user_last_name_max_length', '2026-10-06 14:39:56.350683+00');
INSERT INTO public.django_migrations VALUES (13, 'auth', '0010_alter_group_name_max_length', '2026-10-06 14:39:56.361971+00');
INSERT INTO public.django_migrations VALUES (14, 'auth', '0011_update_proxy_permissions', '2026-10-06 14:39:56.372466+00');
INSERT INTO public.django_migrations VALUES (15, 'auth', '0012_alter_user_first_name_max_length', '2026-10-06 14:39:56.384365+00');
INSERT INTO public.django_migrations VALUES (16, 'accounts', '0001_initial', '2026-10-06 14:39:56.490146+00');
INSERT INTO public.django_migrations VALUES (17, 'admin', '0001_initial', '2026-10-06 14:39:56.511322+00');
INSERT INTO public.django_migrations VALUES (18, 'admin', '0002_logentry_remove_auto_add', '2026-10-06 14:39:56.525528+00');
INSERT INTO public.django_migrations VALUES (19, 'admin', '0003_logentry_add_action_flag_choices', '2026-10-06 14:39:56.537903+00');
INSERT INTO public.django_migrations VALUES (20, 'sessions', '0001_initial', '2026-10-06 14:39:56.549748+00');
INSERT INTO public.django_migrations VALUES (21, 'token_blacklist', '0001_initial', '2026-10-06 14:39:56.581624+00');
INSERT INTO public.django_migrations VALUES (22, 'token_blacklist', '0002_outstandingtoken_jti_hex', '2026-10-06 14:39:56.59484+00');
INSERT INTO public.django_migrations VALUES (23, 'token_blacklist', '0003_auto_20171017_2007', '2026-10-06 14:39:56.610894+00');
INSERT INTO public.django_migrations VALUES (24, 'token_blacklist', '0004_auto_20171017_2013', '2026-10-06 14:39:56.624575+00');
INSERT INTO public.django_migrations VALUES (25, 'token_blacklist', '0005_remove_outstandingtoken_jti', '2026-10-06 14:39:56.63748+00');
INSERT INTO public.django_migrations VALUES (26, 'token_blacklist', '0006_auto_20171017_2113', '2026-10-06 14:39:56.654511+00');
INSERT INTO public.django_migrations VALUES (27, 'token_blacklist', '0007_auto_20171017_2214', '2026-10-06 14:39:56.681537+00');
INSERT INTO public.django_migrations VALUES (28, 'token_blacklist', '0008_migrate_to_bigautofield', '2026-10-06 14:39:56.708656+00');
INSERT INTO public.django_migrations VALUES (29, 'token_blacklist', '0010_fix_migrate_to_bigautofield', '2026-10-06 14:39:56.725871+00');
INSERT INTO public.django_migrations VALUES (30, 'token_blacklist', '0011_linearizes_history', '2026-10-06 14:39:56.730533+00');
INSERT INTO public.django_migrations VALUES (31, 'token_blacklist', '0012_alter_outstandingtoken_user', '2026-10-06 14:39:56.743736+00');
INSERT INTO public.django_migrations VALUES (32, 'token_blacklist', '0013_alter_blacklistedtoken_options_and_more', '2026-10-06 14:39:56.758493+00');
INSERT INTO public.django_migrations VALUES (33, 'referentiel', '0001_initial', '2026-10-06 16:18:54.127566+00');
INSERT INTO public.django_migrations VALUES (34, 'accounts', '0002_organisation_domaines', '2026-10-06 16:18:54.165361+00');
INSERT INTO public.django_migrations VALUES (35, 'referentiel', '0002_renommer_categorie_en_secteur', '2026-10-06 16:43:15.271534+00');
INSERT INTO public.django_migrations VALUES (36, 'accounts', '0003_renommer_domaines_en_secteurs', '2026-10-06 16:43:15.318829+00');
INSERT INTO public.django_migrations VALUES (37, 'accounts', '0004_habilitation_simplifiee', '2026-10-06 16:43:15.456052+00');
INSERT INTO public.django_migrations VALUES (38, 'medias', '0001_initial', '2026-10-06 17:10:25.397521+00');
INSERT INTO public.django_migrations VALUES (39, 'signalements', '0001_initial', '2026-10-06 18:50:50.258698+00');
INSERT INTO public.django_migrations VALUES (40, 'suggestions', '0001_initial', '2026-10-06 19:15:46.960376+00');
INSERT INTO public.django_migrations VALUES (41, 'suggestions', '0002_sans_statut_avec_pertinence', '2026-10-06 19:46:52.174009+00');
INSERT INTO public.django_migrations VALUES (42, 'realisations', '0001_initial', '2026-10-06 19:57:01.837714+00');
INSERT INTO public.django_migrations VALUES (43, 'notifications', '0001_initial', '2026-10-06 21:47:16.736029+00');


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 43, true);


--
-- PostgreSQL database dump complete
--

\unrestrict t3hA2CJxLwPvbrYoeLCUdzHtk4blY2HFUakTvthELNpjUo9c5I4g0zXbGQHuu9D

