# Generated by Django 5.2.18 on 2026-10-06 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('departement', models.CharField(max_length=100, verbose_name='département')),
                ('lat_min', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude minimale')),
                ('lat_max', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude maximale')),
                ('lng_min', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude minimale')),
                ('lng_max', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude maximale')),
            ],
            options={
                'verbose_name': 'commune',
                'verbose_name_plural': 'communes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrondissements', to='territoire.commune', verbose_name='commune')),
            ],
            options={
                'verbose_name': 'arrondissement',
                'verbose_name_plural': 'arrondissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('latitude_centre', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude du centre')),
                ('longitude_centre', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude du centre')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartiers', to='territoire.arrondissement', verbose_name='arrondissement')),
            ],
            options={
                'verbose_name': 'quartier',
                'verbose_name_plural': 'quartiers',
                'ordering': ['nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='arrondissement',
            constraint=models.UniqueConstraint(fields=('commune', 'nom'), name='arrondissement_unique_par_commune', violation_error_message='Cet arrondissement existe déjà dans cette commune.'),
        ),
        migrations.AddConstraint(
            model_name='quartier',
            constraint=models.UniqueConstraint(fields=('arrondissement', 'nom'), name='quartier_unique_par_arrondissement', violation_error_message='Ce quartier existe déjà dans cet arrondissement.'),
        ),
    ]
