# Generated by Django 5.2.18 on 2026-10-06 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('type', models.CharField(choices=[('STATUT_SIGNALEMENT', "Changement de statut d'un signalement"), ('REPONSE_SIGNALEMENT', 'Réponse de la mairie à un signalement'), ('REPONSE_SUGGESTION', 'Réponse de la mairie à une suggestion'), ('NOUVELLE_REALISATION', 'Nouvelle réalisation publiée')], max_length=30, verbose_name='type')),
                ('titre', models.CharField(max_length=150, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('cible_type', models.CharField(choices=[('signalement', 'Signalement'), ('suggestion', 'Suggestion'), ('realisation', 'Réalisation')], max_length=20, verbose_name='type de cible')),
                ('cible_id', models.BigIntegerField(verbose_name='identifiant de la cible')),
                ('lu', models.BooleanField(default=False, verbose_name='lue')),
                ('envoye_push', models.BooleanField(default=False, verbose_name='envoyée en push')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-cree_le', '-id'],
                'indexes': [models.Index(fields=['destinataire', 'lu'], name='notification_destinataire_lu')],
            },
        ),
    ]
